title : tsphethean.co.uk
tagline: 
author :
  name : Tom Phethean
  email : blah@email.test
  github : tsphethean
  twitter : tsphethean
  feedburner : 

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
